### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Nerian**

### CODE REVIEW

**Comment by matt-riemer** [comment]
Nah, it can't be `authorize!`, that's an actual CanCan method!  (I use CanCan, so I'd know hehe).

This is the right idea tho, I'll take a look at it again.

**Comment by Nerian** [comment]
Oh sure, I never used cancan. Feel free to change to whatever name you want :)

**Comment by matt-riemer** [comment]
Do you roll your own auth then?  It seems like CanCan and Pundit are the two big ones...

I'm on the whole devise / cancan / turbolinks, haml & simple_form toolchain :)

**Comment by Nerian** [comment]
I use Sorcery (https://github.com/NoamB/sorcery) for authentication. It is a super simple DSL and let me put things where I want to. It gives you some methods and you decide where you put them.

For authorization I just have some custom before filters; that works for me for now, but I can totally see myself switching to CanCan once I get to implement the role system. I am implementing a software for coworking spaces:  https://www.coku-app.com/

Turbolinks is awesome, and it really pays off to use event oriented programming for the UI.  SimpleForms may be the best project in the rails ecosystem.

HAML is lovely; I am using Slim, it's pretty similar.

**Comment by matt-riemer** [comment]
I should give Sorcery a try on my next project.  Been using Devise forever, and it's good, but fairly bloated.  Similar story to slim, I wanna make the change from haml, for those speed ups, but haven't quite got there yet :)

Software for co-working spaces? very cool....So many businesses just don't know where to go for invoicing and payment software.  There's a lot of offerings out there, but they're usually just single invoice fire and forget kind of things.  This is a neat idea with batching a whole bunch of payments then releasing one invoice at a time.  I could see a lot of organizations wanting something like this.

I'm the lead developer at a rails consultancy shop here in Canada, we work with a lot of medium sized organizations to build software that runs their day to day operations

http://codeandeffect.com

We try to open source a lot of our code.  I use:

https://github.com/code-and-effect/effective_roles
https://github.com/code-and-effect/effective_orders

and a bunch of the other ones on a lot of our sites.

**Pull request closed without merging**
