### PR TITLE
Add bulk-action for submitting via POST form

### PR DESCRIPTION
**Pull request by Nerian**
Hello,

This PR add support for using a POST with a form submission when using bulk-actions. This is useful for when you need to send several thousand ids.

### CODE REVIEW

**Comment by matt-riemer** [comment]
I like the idea of this PR. Could you update the indenting on those if statements so it reads better? I'm confused what code actually gets executed :)

This is kind of a standard form POST that will refresh the entire page, instead of an AJAX response like the GET or the file download (which is a post).  Maybe this is another kind of bulk operation? what do you think? :)

**Comment by Nerian** [comment]
> I like the idea of this PR. Could you update the indenting on those if statements so it reads better? I'm confused what code actually gets executed :)

Sorry, I am not sure what you mean about the indenting. Do you want me to add the if/else? I agree it has become quite long :) Maybe some refactoring would be nice.

> This is kind of a standard form POST that will refresh the entire page, instead of an AJAX response like the GET or the file download (which is a post). Maybe this is another kind of bulk operation? what do you think? :)

In my case I use like this: The user will use filters to narrow down a number of expedients, and then select a few or all. He will then click on the bulk action and do a POST to some action. The action will receive a list of ids, and render a form for further options for processing the selected expedients; the expedient ids will be rendered in the form via hidden fields. It's sort of a wizard pattern.

Maybe we could re-categorise all the options. Right now we differentiate between GET and POST and then another modifier. Maybe we should try to just provide one category.

From this:
```
data: { method: :get }
data: { 'payload-mode' => 'local-storage', method: :get }
data: { 'payload-mode' => 'cookie', method: :get }
data: { 'payload-mode' => 'form', method: :post }
```

To this:
```
data: { 'payload-mode' => 'form', method: :post }
data: { 'payload-mode' => 'form', method: :post }
data: { 'payload-mode' => 'form', method: :post }
```

**Comment by Nerian** [comment]
Hi,

Why close it? Do I need to rework anything? My last comment included some questions about what we could do it. Let me know.

**Comment by matt-riemer** [comment]
I don't want to make changes here because I have many legacy apps that would need updating.

I don't like the original code, or the new code 'cause it's too complex, basically unreadable and has no testing :(

**Comment by Nerian** [comment]
👌 Will try to refactor the code

**Comment by Nerian** [comment]
👋   Feel free to close this PR. I will find a different way to implement this own code.

**Pull request closed without merging**
